src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone_num;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $job;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPhoneNum(): ?string
    {
        return $this->phone_num;
    }

    public function setPhoneNum(string $phone_num): self
    {
        $this->phone_num = $phone_num;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }
}

src/Controller/AcceuilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AcceuilController extends AbstractController
{
    /**
     * @Route("/acceuil", name="acceuil", methods={"GET"})
     */
    public function index(): Response
    {
        $nom = "steph";
        return $this->render('acceuil/index.html.twig', [
            'leNom' => $nom,
            'controller_name' => 'AcceuilController'
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Repository\ContactRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ContactController extends AbstractController
{
    /**
     * @Route("/contacts", name="contacts", methods={"GET"})
     */
    public function listeContacts(ContactRepository $repo): Response
    {
      
        // $manager = $this -> getDoctrine() -> getManager();
        // $repo = $manager -> getRepository(Contact::class);
        $contacts = $repo-> findAll();
            
        return $this->render('contact/listeContacts.html.twig', [
            'controller_name' => 'ContactController',
            'lesContacts' => $contacts
        ]);
    }
    /**
     * @Route("/contactsByName", name="contactsByName", methods={"GET"})
     */
    public function ContactByName(ContactRepository $repo): Response
    {
        $contactsByName = $repo ->  findByOrderedColumn("nom");
            
        return $this->render('contact/contactsByName.html.twig', [
            'controller_name' => 'ContactController',
            'contactsByName' => $contactsByName
        ]);
    }
    /**
     * @Route("/contactsByJob", name="contactsByJob", methods={"GET"})
     */
    public function contactsByJob(ContactRepository $repo): Response
    {
        $contactsByJob = $repo ->  findByOrderedColumn("job");
            
        return $this->render('contact/contactsByJob.html.twig', [
            'controller_name' => 'ContactController',
            'contactsByJob' => $contactsByJob
        ]);
    }
    /**
     * @Route("/contactsByFirstName", name="contactsByFirstName", methods={"GET"})
     */
    public function contactsByFirstName(ContactRepository $repo): Response
    {
        $contactsByFirstName = $repo ->  findByOrderedColumn("prenom");
            
        return $this->render('contact/contactsByFirstName.html.twig', [
            'controller_name' => 'ContactController',
            'contactsByFirstName' => $contactsByFirstName
        ]);
    }
    /**
     * @Route("/contactsByPhone", name="contactsByPhone", methods={"GET"})
     */
    public function contactsByPhone(ContactRepository $repo): Response
    {
        $contactsByPhone = $repo ->  findByOrderedColumn("phone_num");
            
        return $this->render('contact/contactsByPhone.html.twig', [
            'controller_name' => 'ContactController',
            'contactsByPhone' => $contactsByPhone
        ]);
    }
    /**
     * @Route("/contactsByCompany", name="contactsByCompany", methods={"GET"})
     */
    public function contactsByCompany(ContactRepository $repo): Response
    {
        $contactsByCompany = $repo ->  findByOrderedColumn("company_name");
            
        return $this->render('contact/contactsByCompany.html.twig', [
            'controller_name' => 'ContactController',
            'contactsByCompany' => $contactsByCompany
        ]);
    }
}

templates/acceuil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acceuil{% endblock %}

{% block body %}
{{leNom}}
<h1 class="text-center pt-5">Bienvenue sur mon application de gestion</h1>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        {% block stylesheets %} {% endblock %}

    </head>
    <body>
    {# navbar #}
        <nav class="navbar navbar-expand-lg navbar bg-primary" data-bs-theme="dark" >
            <div class="container-fluid">
                <a class="navbar-brand" href="{{path('acceuil')}}">Acceuil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{{path('contacts')}}">Mes contacts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                     
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
        {% block body %}{% endblock %} 
        </div>

        {% block javascripts %} {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </body>
</html>

templates/contact/ContactsByCompany.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><a href="{{path('contacts')}}">ID</a></th>
      <th scope="col" ><a href="{{path('contactsByFirstName')}}">Prenom</a></th>
      <th scope="col" ><a href="{{path('contactsByName')}}">Nom</a></th>
      <th scope="col" ><a href="{{path('contactsByPhone')}}">Numéro tel</a></th>
      <th scope="col"><a href="{{path('contactsByJob')}}">Job</a></th>
      <th scope="col">Entreprise</th>
    </tr>
  </thead>
  <tbody>
  {% for contact in contactsByCompany %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/contact/ContactsByFirstName.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><a href="{{path('contacts')}}">ID</a></th>
      <th scope="col">Prenom</th>
      <th scope="col" ><a href="{{path('contactsByName')}}">Nom</a></th>
      <th scope="col" ><a href="{{path('contactsByPhone')}}">Numéro tel</a></th>
      <th scope="col"><a href="{{path('contactsByJob')}}">Job</a></th>
      <th scope="col"><a href="{{path('contactsByCompany')}}">Entreprise</a></th>
    </tr>
  </thead>
  <tbody>
  {% for contact in contactsByFirstName %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/contact/ContactsByJob.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><a href="{{path('contacts')}}">ID</a></th>
      <th scope="col" ><a href="{{path('contactsByFirstName')}}">Prenom</a></th>
      <th scope="col" ><a href="{{path('contactsByName')}}">Nom</a></th>
      <th scope="col" ><a href="{{path('contactsByPhone')}}">Numéro tel</a></th>
      <th scope="col">Job</th>
       <th scope="col"><a href="{{path('contactsByCompany')}}">Entreprise</a></th>
    </tr>
  </thead>
  <tbody>
  {% for contact in contactsByJob %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/contact/ContactsByName.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><a href="{{path('contacts')}}">ID</a></th>
      <th scope="col" ><a href="{{path('contactsByFirstName')}}">Prenom</a></th>
      <th scope="col">Nom</th>
      <th scope="col" ><a href="{{path('contactsByPhone')}}">Numéro tel</a></th>
      <th scope="col"><a href="{{path('contactsByJob')}}">Job</a></th>
       <th scope="col"><a href="{{path('contactsByCompany')}}">Entreprise</a></th>
    </tr>
  </thead>
  <tbody>
  {% for contact in contactsByName %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/contact/ContactsByPhone.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><a href="{{path('contacts')}}">ID</a></th>
      <th scope="col" ><a href="{{path('contactsByFirstName')}}">Prenom</a></th>
      <th scope="col" ><a href="{{path('contactsByName')}}">Nom</a></th>
      <th scope="col">Numéro tel</th>
      <th scope="col"><a href="{{path('contactsByJob')}}">Job</a></th>
      <th scope="col"><a href="{{path('contactsByCompany')}}">Entreprise</a></th>
    </tr>
  </thead>
  <tbody>
  {% for contact in contactsByPhone %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/contact/listeContacts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste contacts


{% endblock %}

{% block body %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
       <th scope="col" ><a href="{{path('contactsByFirstName')}}">Prenom</a></th>
      <th scope="col" ><a href="{{path('contactsByName')}}">Nom</a></th>
      <th scope="col" ><a href="{{path('contactsByPhone')}}">Numéro tel</a></th>
      <th scope="col"><a href="{{path('contactsByJob')}}">Job</a></th>
      <th scope="col"><a href="{{path('contactsByCompany')}}">Entreprise</a></th>
    </tr>
  </thead>
  <tbody>
  {% for contact in lesContacts %}
    <tr class="table-active">
    
      <td>{{contact.id}}</td>
      <td>{{contact.prenom}}</td>
      <td>{{contact.nom}}</td>
      <td>{{contact.phoneNum}}</td>
      <td>{{contact.job}}</td>
      <td>{{contact.companyName}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}